version: "3"

services:
  db:
#    image: mysql:8.3
    image: mysql
    ports:
      #      - "3306:3306"
      - "3308:3306"
    container_name: mysql-container2
    volumes:
      - mysql-data:/var/lib/mysql
#    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: valletta
#      MYSQL_USER: root
#      MYSQL_PASSWORD: 1234
#    networks:
#      - django-network
    healthcheck:
#      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD']
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
#      interval: 10s
#      timeout: 2s
#      retries: 100
      interval: 1m30s
      timeout: 3m
      retries: 100

  app:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
#    entrypoint: sh -c "python manage.py collectstatic --no-input && python manage.py migrate && gunicorn --bind 0:8000 django_project_doit.wsgi:application"
    command: >
      sh -c "python manage.py collectstatic --no-input &&
              python manage.py migrate &&
              gunicorn --bind 0:8000 django_project_doit.wsgi:application"

    ports:
      - "8000:8000"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_HOST: db
    depends_on:
      db:
        condition: service_healthy
#    networks:
#      - django-network

#networks:
#  django-network:

volumes:
  mysql-data:
