version: "3"

services:
  db:
    image: mysql:8.3
    ports:
      - "3306:3306"
    container_name: mysql-container
    volumes:
      - mysql-data:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --colation-server=utf8_general_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: valletta
#      MYSQL_USER: root
#      MYSQL_PASSWORD: 1234
    networks:
      - django-network
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD']
      interval: 10s
      timeout: 2s
      retries: 100

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_HOST: db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - django-network

networks:
  django-network:

volumes:
  mysql-data:
