[tool.poetry]
name = "django-study-doit"
version = "0.1.0"
description = ""
authors = ["주현(백엔드개발1팀) <rich@hanssem.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
